/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3s152OPpbyA
 */
import { Button } from "@/components/ui/button"

export default function CardDisplay({onClose}) {
  return (
    (    <div className="bg-[#AF1414] max-w-4xl mx-auto my-8 p-8 rounded-xl text-white relative">
    <button onClick={onClose}className="absolute top-2 right-2 bg-white text-[#bd1e59] rounded-full p-2">
      <CloseIcon className="w-6 h-6" />
    </button>
      <h2 className="text-3xl font-bold mb-6">Toyota Camry XL Premium</h2>
      <div className="relative">
        <button
          className="absolute left-0 top-1/2 transform -translate-y-1/2 bg-white text-[#bd1e59] rounded-full p-4">
          <ChevronLeftIcon className="w-6 h-6" />
        </button>
        <div className="flex gap-4 overflow-hidden">
          <div
            className="bg-white p-6 rounded-lg shadow-md flex items-center justify-center">
            <img
              alt="Car Image 1"
              className="object-cover rounded-lg"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400} />
          </div>
          <div
            className="bg-white p-6 rounded-lg shadow-md flex items-center justify-center">
            <img
              alt="Car Image 2"
              className="object-cover rounded-lg"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400} />
          </div>
          <div
            className="bg-white p-6 rounded-lg shadow-md flex items-center justify-center">
            <img
              alt="Car Image 3"
              className="object-cover rounded-lg"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400} />
          </div>
        </div>
        <button
          className="absolute right-0 top-1/2 transform -translate-y-1/2 bg-white text-[#bd1e59] rounded-full p-4">
          <ChevronRightIcon className="w-6 h-6" />
        </button>
      </div>
      <div className="mt-8">
        <p className="text-lg text-white">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua.
        </p>
        <Button className="bg-white text-[#bd1e59] w-full py-4 rounded-full mt-4">Schedule Appointment</Button>
      </div>
    </div>)
  );
}
function CloseIcon(props) {
  return (
    <svg {...props} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
    </svg>
  );
}

function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}
